#! /usr/bin/env python3
########################################################################
# Copyright (C) 2014, David Arnold.
# All rights reserved.
#
# This file is part of alog.
#
# alog is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# alog is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with btpm; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
#
########################################################################

import sys

def main():
    pass

if __name__ == "__main__":
    main()


########################################################################
# Local Variables:
# mode: python
# End:
########################################################################
